export type InspectionOption = {
  name: string;
  label: string;
};

export type InspectionCategory = {
  name: string;
  label: string;
  order: number;
  options: InspectionOption[];
};

export const inspectionSchema = {
  preInspection: [
    {
      name: "rams_info_submitted",
      label: "RAMS information submitted",
      order: 1,
    },
    {
      name: "wall_type_drawings",
      label: "Wall Type Drawings available",
      order: 2,
    },
    { name: "induction_arranged", label: "Induction arranged", order: 3 },
    { name: "induction_attended", label: "Induction attended", order: 4 },
    {
      name: "ppe_checked",
      label: "PPE (incl glasses and sleeves for Wates)",
      order: 5,
    },
    {
      name: "client_meeting",
      label: "Meet with client representative",
      order: 6,
    },
    {
      name: "fire_drawings_available",
      label: "Latest fire strategy drawings available",
      order: 7,
    },
    { name: "bolster_uploads", label: "Bolster uploads completed", order: 8 },
    {
      name: "bolster_synced",
      label: "Bolster down synced and checked",
      order: 9,
    },
    {
      name: "latest_eta_available",
      label: "Latest Manufacturer ETAs",
      order: 10,
    },
    {
      name: "walkthrough_done",
      label: "Walk through and cursory inspection",
      order: 11,
    },
  ],

  projectInformation: [
    { name: "project_name", label: "Project Name", order: 1 },
    { name: "project_reference", label: "Project Reference", order: 2 },
    {
      name: "inspection_date",
      label: "Inspection Date",
      order: 3,
      type: "date",
    },
    { name: "inspection_number", label: "Inspection Number", order: 4 },
    { name: "client", label: "Client", order: 5 },
    { name: "client_contact", label: "Client Contact & Title", order: 6 },
    { name: "client_rep", label: "Client Site Rep & Title", order: 7 },
    { name: "installer", label: "Installer/contractor", order: 8 },
    { name: "third_party_acr", label: "3rd Party Acc. Body", order: 9 },
    { name: "digital_recording", label: "Digital Recording", order: 10 },
    { name: "storeys", label: "Storeys", order: 11, type: "number" },
    {
      name: "structural_frame",
      label: "Structural Frame",
      order: 12,
      options: ["Structural Steel", "SFS", "Concrete"],
    },
    {
      name: "facade",
      label: "Façade",
      order: 13,
      options: [
        "Brick",
        "Glazing",
        "Swiss Pearl",
        "Curtain Wall",
        "Rain Screen Cladding",
        "SFS framed internal leaf",
      ],
    },
    {
      name: "floor_type",
      label: "Floor Type",
      order: 14,
      options: [
        "Hollowcore",
        "Pre-cast Concrete planks",
        "Composite concrete decking",
        "timber",
        "CLT",
      ],
    },
    {
      name: "internal_walls",
      label: "Internal Walls Types",
      order: 15,
      options: ["Blockwork", "Flexible Wall", "Concrete"],
    },
    {
      name: "encasements",
      label: "Encasements",
      order: 16,
      options: ["Knauf", "British Gypsum", "Promat", "Siniat"],
    },
    {
      name: "flexible_wall_manufacturer",
      label: "Flexible Wall Manufacturer",
      order: 17,
      options: ["British Gypsum", "Knauf", "Sinat"],
    },
    {
      name: "fire_stopping_materials",
      label: "Fire Stopping Materials",
      order: 18,
      options: [
        "Quelfire",
        "Nullifire",
        "Hilti",
        "Protecta",
        "Rockwool",
        "FSi",
      ],
    },
    {
      name: "barrier_materials",
      label: "Barrier materials - external",
      order: 19,
      options: [
        "N/A",
        "Siderise",
        "Rockwool",
        "Nullifire",
        "FSi",
        "Tenmat",
        "AIM",
      ],
    },
    {
      name: "barrier_materials_raf",
      label: "Barrier materials - RAF",
      order: 20,
      options: ["N/A", "Siderise", "Quelfire", "AIM", "Protecta"],
    },
    {
      name: "barrier_materials_ceiling",
      label: "Barrier materials - Ceiling void",
      order: 21,
      options: ["N/A", "TBA Firefly", "Rockwool"],
    },
    {
      name: "dampers",
      label: "Dampers",
      order: 22,
      options: [
        "Trox",
        "BSB",
        "Swegon ActionAir",
        "Advanced Air",
        "Lindab",
        "NCA",
      ],
    },
    {
      name: "fire_rated_ductwork",
      label: "Fire Rated Ductwork",
      order: 23,
      options: ["Caswell", "Firemac", "Thorduct"],
    },
  ],

  siteInspections: [
    {
      name: "cavity_barriers_external",
      label: "External barriers",
      order: 1,
      options: [
        { name: "substrate", label: "substrate" },
        { name: "compression", label: "compression" },
        { name: "brackets", label: "brackets" },
        { name: "fixings", label: "fixings" },
        { name: "joints", label: "joints" },
        { name: "sealants", label: "sealants" },
        { name: "tapes", label: "tapes" },
      ],
    },
    {
      name: "cavity_barriers_raf",
      label: "Cavity Barriers, RAF",
      order: 2,
      options: [
        { name: "compression", label: "compression" },
        { name: "brackets", label: "brackets" },
        { name: "fixings", label: "fixings" },
        { name: "joints", label: "joints" },
        { name: "sealants", label: "sealants" },
        { name: "tapes", label: "tapes" },
        { name: "penetration_seals", label: "penetration seals" },
      ],
    },
    {
      name: "cavity_barriers_ceiling_void",
      label: "Cavity Barriers, ceiling void",
      order: 3,
      options: [
        { name: "substrate", label: "substrate" },
        { name: "brackets", label: "brackets" },
        { name: "fixings", label: "fixings" },
        { name: "joints", label: "joints" },
        { name: "overlaps", label: "overlaps" },
        { name: "stitching", label: "stitching" },
        { name: "stapling", label: "stapling" },
        { name: "penetrations", label: "penetrations" },
        { name: "collars_sleeves", label: "collars/ sleeves" },
      ],
    },
    {
      name: "deflection_head",
      label: "Deflection Head",
      order: 4,
      options: [
        { name: "fixings", label: "fixings" },
        { name: "junctions", label: "junctions" },
        { name: "deflection_allowance", label: "deflection allowance" },
        { name: "dry-lining_overlap", label: "dry-lining overlap" },
        { name: "overlaps", label: "overlaps" },
        { name: "cloaking_angle_strip", label: "cloaking angle/ strip" },
        { name: "gaps_breaches_voids", label: "gaps/breaches/ voids" },
        {
          name: "intumescent_strips_sealant",
          label: "intumescent strips/ sealant",
        },
      ],
    },
    {
      name: "3_sided_bwic",
      label: "3-sided BWIC",
      order: 5,
      options: [
        { name: "framing", label: "framing" },
        { name: "lining", label: "lining" },
        { name: "tape_jointing", label: "tape & jointing" },
        { name: "fixings", label: "fixings" },
        {
          name: "сompressible_fire",
          label: "сompressible fire seal if deflection required",
        },
      ],
    },
    {
      name: "4_sided_bwic",
      label: "4-sided BWIC",
      order: 6,
      options: [
        { name: "framing", label: "framing" },
        { name: "lining", label: "lining" },
        { name: "tape_jointing", label: "tape & jointing" },
        { name: "fixings", label: "fixings" },
      ],
    },
    {
      name: "wall_makeup",
      label: "Wall Makeup",
      order: 7,
      options: [
        { name: "layers", label: "layers" },
        { name: "thickness", label: "thickness" },
        { name: "framing_system", label: "framing system" },
      ],
    },
    {
      name: "fire_stopping_friction_fitted",
      label: "Fire Stopping, Friction Fitted",
      order: 8,
      options: [
        { name: "opening", label: "opening (size/spacing etc)" },
        { name: "service_spacing", label: "service spacing" },
        { name: "layers", label: "layers" },
        { name: "edge_joint_coating", label: "edge/joint coating" },
        { name: "lagging", label: "lagging" },
        { name: "closure_devices", label: "closure devices" },
        { name: "service_supports", label: "service supports" },
        { name: "fitted_es", label: "fitted e/s" },
        { name: "fixings", label: "fixings" },
        { name: "compression", label: "compression" },
      ],
    },
    {
      name: "fire_stopping_horizontal",
      label: "Fire Stopping, Horizontal",
      order: 9,
      options: [
        { name: "substrate", label: "substrate" },
        { name: "shutter", label: "shutter" },
        { name: "layers", label: "layers" },
        { name: "depth", label: "depth" },
        { name: "closure_devices", label: "closure devices" },
        { name: "fixings", label: "fixings" },
        { name: "lagging", label: "lagging" },
        { name: "supports", label: "supports" },
      ],
    },
    {
      name: "fire_stopping_face_fixed",
      label: "Fire Stopping, Face Fixed",
      order: 10,
      options: [
        { name: "fixings", label: "fixings" },
        { name: "overlaps", label: "overlaps" },
        { name: "service_spacing", label: "service spacing" },
        { name: "closure_devices", label: "closure devices" },
        { name: "lagging", label: "lagging" },
        { name: "edge_coating", label: "edge coating" },
        { name: "service_supports", label: "service supports" },
      ],
    },
    {
      name: "fire_stopping_closure_devices",
      label: "Fire Stopping, Closure Devices",
      order: 11,
      options: [
        { name: "pipe_type", label: "pipe/insulation type/diameter" },
        { name: "annulus", label: "annulus" },
        { name: "depth", label: "depth" },
        { name: "layers", label: "layers" },
        { name: "fixings", label: "fixings" },
        { name: "diameter", label: "diameter" },
        { name: "fitted_to_plain_pipe", label: "fitted to plain pipe" },
      ],
    },
    {
      name: "dampers",
      label: "Dampers",
      order: 12,
      options: [
        { name: "opening", label: "opening (size/spacing etc)" },
        { name: "opening_infill", label: "opening infill" },
        { name: "dimensions_to_casing", label: "dimensions to casing" },
        { name: "fixings", label: "fixings" },
        { name: "supports", label: "supports" },
        { name: "plasterboard_pattress", label: "plasterboard pattress" },
      ],
    },
    {
      name: "encasements",
      label: "Encasements",
      order: 13,
      options: [
        { name: "thickness", label: "thickness" },
        { name: "fixing", label: "fixing(type/centres/orientation)" },
        { name: "framing", label: "framing" },
        { name: "joints", label: "joints" },
        { name: "junctions", label: "junctions" },
        { name: "overlaps", label: "overlaps" },
        { name: "any_penetrations", label: "any penetrations" },
      ],
    },
    {
      name: "linear_joint_seals",
      label: "Linear Joint Seals",
      order: 14,
      options: [
        { name: "compression", label: "compression" },
        { name: "gap_size", label: "gap size" },
        { name: "depth", label: "depth" },
        { name: "sealant", label: "sealant" },
        { name: "backing_material", label: "backing material" },
      ],
    },
    {
      name: "putty_pads",
      label: "Putty Pads",
      order: 15,
      options: [
        { name: "sealed", label: "sealed" },
        { name: "suitable_openings_size", label: "suitable openings size" },
        { name: "spacing_of_opening", label: "spacing of opening" },
        {
          name: "in_line_with_plasterboard",
          label: "in line with plasterboard",
        },
        { name: "plasterboard_sealed", label: "plasterboard sealed" },
      ],
    },
    {
      name: "trapezoidal_voids",
      label: "Trapezoidal Voids",
      order: 16,
      options: [
        { name: "infilled", label: "infilled" },
        { name: "sealant", label: "sealant" },
      ],
    },
    {
      name: "destructive_tests",
      label: "Destructive Tests",
      order: 17,
      options: [{ name: "carried_out", label: "carried out?" }],
    },
  ],

  postInspection: [
    {
      name: "client_meeting_done",
      label: "Meet with client representative",
      order: 1,
    },
    {
      name: "next_inspection_date",
      label: "Date of next inspection visit",
      order: 2,
      type: "date",
    },
    { name: "urgent_matters", label: "Communicate urgent matters", order: 3 },
    { name: "bolster_notes", label: "Up-sync Bolster", order: 4 },
    { name: "comment", label: "Comment", order: 5 },
  ],
};
